import {StyleSheet} from 'react-native';
import {colors, WP, fontFamilies, lineHeights} from '../../../../../services';

export default () =>
  StyleSheet.create({
    logo: {
      alignSelf: 'center',
      height: 40,
      width: 40,
      margin: 10,
      marginTop: 22,
    },
    imageS: {
      alignSelf: 'center',
      height: 80,
      width: 80,
      margin: 10,
      marginTop: 22,
    },
    headerText: {
      width: WP('100'),
      padding: 10,
      color: colors.skyBlue,
      textAlign: 'center',
      fontSize: 18,
      fontFamily: fontFamilies('boldTextHeader'),
    },
    headerTitle: {
      // width: WP('100'),
      padding: 10,
      color: colors.skyBlue,
      textAlign: 'center',
      fontSize: 18,
      fontFamily: fontFamilies('boldTextHeader'),
    },
    amountColor: {
      color: colors.skyBlue,
      paddingBottom: 10,
    },
    flexWrap: {
      flex: 1,
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginTop: 10,
    },
    invoiceSummary: {
      padding: 8,
      color: colors.black,
      textAlign: 'center',
      fontSize: 18,
      fontFamily: fontFamilies('boldTextHeader'),
    },
    invoiceSummaryDetail: {
      // padding: 2,
      color: colors.black,
      // textAlign: 'center',
      fontSize: 14,
      fontFamily: fontFamilies('boldTextHeader'),
      // paddingLeft:5,
      paddingRight: 5,
      paddingBottom: 2,
    },
    paddingLeft: {
      paddingLeft: 5,
    },
    invoiceSummaryDetailText: {
      paddingLeft: 5,
      paddingRight: 5,
      color: colors.mediumGrey,
      fontSize: 14,
      // fontFamily: fontFamilies('boldTextHeader'),
    },
    innerCard: {
      padding: 2,
      backgroundColor: '#FFFFFF',
      borderRadius: 10,
      marginTop: 10,
      marginHorizontal: 5,
      shadowColor: 'rgba(0,0,0, .4)',
      shadowOffset: {height: 1, width: 1},
      shadowOpacity: 1,
      shadowRadius: 1,
      elevation: 5,
    },
    innerContainer: {
      width: WP('92'),
      alignSelf: 'center',
    },
    card: {
      backgroundColor: '#FFFFFF',
      borderRadius: 15,
      marginTop: 12,
      marginHorizontal: 5,
      shadowColor: 'rgba(0,0,0, .4)',
      shadowOffset: {height: 1, width: 1},
      shadowOpacity: 1,
      shadowRadius: 1,
      elevation: 5,
    },
    scrollViewContainer: {
      width: WP('100'),
      alignSelf: 'center',
    },
    imageStyle: {
      alignSelf: 'center',
      height: 30,
      width: 30,
      margin: 10,
      marginTop: 26,
    },
    invoice: {
      backgroundColor: colors.red,
      marginRight: 3,
      borderBottomLeftRadius: 15,
      borderTopLeftRadius: 15,
    },
    invoiceNo: {
      color: colors.black,
      fontSize: 16,
      // textAlign: 'center',
      fontFamily: fontFamilies('boldText'),
      marginTop: 10,
      fontWeight: 'bold',
      // textAlign:'right'
      // height:50
    },
    payText: {
      textAlign: 'right',
      marginRight: 30,
      backgroundColor: colors.greens,
      color: colors.white,
      // padding:10,
      marginTop: 10,
      borderRadius: 10,
      paddingLeft: 15,
      paddingBottom: 7,
      paddingRight: 15,
      paddingTop: 7,
      fontWeight: 'bold',
    },
    creditcardcheck: {
      flex: 1,
      // borderColor: colors.primary,
      // borderWidth: 1,
      // marginBottom: 30,
      borderRadius: 20,
      margin: 3,
      backgroundColor: colors.primary,
    },
    stepText: {
      color: colors.darkGrey,
      paddingVertical: 5,
      textAlign: 'left',
    },
    scrollContainer: {
      width: WP('100'),
    },
    selectText: {
      color: colors.black,
      fontSize: 18,
      paddingVertical: 10,
      textAlign: 'left',
    },
    searchContainer: {
      paddingHorizontal: 10,
      backgroundColor: colors.extraLightGrey,
      borderRadius: 10,
      flexDirection: 'row',
      alignItems: 'center',
    },
    searchInput: {
      padding: 15,
      color: colors.darkGrey,
      textAlign: 'left',
      fontFamily: fontFamilies('normalText'),
    },
    innerContainer: {
      width: WP('92'),
      alignSelf: 'center',
    },
  });
