export const registerReducerTypes = {
  REGISTER_USER: 'REGISTER_USER',
  SET_USER_LOADING: 'SET_USER_LOADING',
  SET_REGISTER_ERRORS: 'SET_REGISTER_ERRORS',
  SET_LOGEDIN_USER: 'SET_LOGEDIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  SET_FCM_TOKEN: 'SET_FCM_TOKEN',
};

export const invoiceAndPaymentReducer = {
  GET_INVOICE: 'GET_INVOICE',
  SET_LOADING: 'SETLOADING',
};
export const GalleryReducerTypes = {
  SET_LOADING: 'SET_LOADING',
  SET_ERRORS: 'SET_ERRORS',
  SET_ALL_IMAGES: 'SET_ALL_IMAGES',
  DELETE_IMAGE: 'DELETE_IMAGE',
};
export const inpatientServicesTypes = {
  GET_INPATIENT: 'GET_INPATIENT',
  SET_INPATIENT_LOADING: 'SET_INPATIENT_LOADING',
  GET_INPATIENT_REQUESTS: 'GET_INPATIENT_REQUESTS',
};

export const flowerServiceTypes = {
  GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
  GET_ALL_ORDERS: 'GET_ALL_ORDERS',
  CLEAR_CART_ITEMS: 'CLEAR_CART_ITEMS',
  UPDATE_ORDER: 'UPDATE_ORDER',
  ADD_TO_CART: 'ADD_TO_CART',
  COUNT_UP: 'COUNT_UP',
  COUNT_DOWN: 'COUNT_DOWN',
  DELETE_CART_ITEM: 'DELETE_CART_ITEM',
  MAKE_ORDER: 'MAKE_ORDER',
  UPDATED_CART_ITEMS: 'UPDATED_CART_ITEMS',
  RATE_ORDER: 'RATE_ORDER',
};

export const restaurantTypes = {
  GET_ALL_PRODUCTS_RESTAURANT: 'GET_ALL_PRODUCTS_RESTAURANT',
  GET_ALL_ORDERS_RESTAURANT: 'GET_ALL_ORDERS_RESTAURANT',
  CLEAR_CART_ITEMS_RESTAURANT: 'CLEAR_CART_ITEMS_RESTAURANT',
  UPDATE_ORDER_RESTAURANT: 'UPDATE_ORDER_RESTAURANT',
  ADD_TO_CART_RESTAURANT: 'ADD_TO_CART_RESTAURANT',
  COUNT_UP_RESTAURANT: 'COUNT_UP_RESTAURANT',
  COUNT_DOWN_RESTAURANT: 'COUNT_DOWN_RESTAURANT',
  DELETE_CART_ITEM_RESTAURANT: 'DELETE_CART_ITEM_RESTAURANT',
  MAKE_ORDER_RESTAURANT: 'MAKE_ORDER_RESTAURANT',
  UPDATED_CART_ITEMS_RESTAURANT: 'UPDATED_CART_ITEMS_RESTAURANT',
  RATE_ORDER_RESTAURANT: 'RATE_ORDER_RESTAURANT',
};
export const themeReducersTypes = {
  SET_THEME: 'SET_THEME',
};

export const homeReducersTypes = {
  SET_ALL_NEWS: 'SET_ALL_NEWS',
  SET_MODAL_DISMISSED: 'SET_MODAL_DISMISSED',
};

export const appointmentReducersTypes = {
  SET_SPECIALITIES_OBJECT: 'SET_SPECIALITIES_OBJECT',
  SET_DOCTORS_OBJECT: 'SET_DOCTORS_OBJECT',
  SET_ALL_DOCTORS_OBJECT: 'SET_ALL_DOCTORS_OBJECT',
  SET_SCHEDULES: 'SET_SCHEDULES',
  SET_LOADER: 'SET_LOADER_APPOINTMENTS',
  SET_MY_APPOINTMENTS: 'SET_MY_APPOINTMENTS',
};

export const paymentsReducersTypes = {
  SET_ALL_CARDS: 'SET_ALL_CARDS',
  SET_SELECTED_CARD: 'SET_SELECTED_CARD',
  SET_CARD_HOLDER: 'SET_CARD_HOLDER',
  SET_CARD_NUMBER: 'SET_CARD_NUMBER',
  SET_EXPIRY: 'SET_EXPIRY',
  SET_CVV_NUMBER: 'SET_CVV_NUMBER',
};

export const reportsReducersTypes = {
  SET_LAB_REPORTS: 'SET_LAB_REPORTS',
  SET_RADIOLOGY_REPORTS: 'SET_RADIOLOGY_REPORTS',
  SET_LAB_REPORTS_DETAILS: 'SET_LAB_REPORTS_DETAILS',
  SET_RADIOLOGY_REPORTS_DETAILS: 'SET_RADIOLOGY_REPORTS_DETAILS',
};

export const cardsReducerTypes = {
  GET_ALL_CARDS: 'GET_ALL_CARDS',
  ADD_NEW_CARD: 'ADD_NEW_CARD',
};

export const vitalSignsTypes = {
  GET_VITAL_SIGNS: 'GET_VITAL_SIGNS',
};

export const patientsTypes = {
  GET_PATIENTS: 'GET_PATIENTS',
  GET_PATIENTS_MEMBER: 'GET_PATIENTS_MEMBER',
};
export const doctorScheduleTypes = {
  GET_SCHEDULE: 'GET_SHCEDULE',
  GET_DAYS_OFF: 'GET_DAYS_OFF'
};

export const InvoiceData = {
  SET_ALL_INVOICE_DATE: 'SET_ALL_INVOICE_DATE',
};
